package com.example.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.greendao.entity.Animal;
import com.example.greendao.entity.Body;
import com.example.greendao.entity.House;
import com.example.greendao.entity.Person;
import com.example.greendao.entity.PersonWithHouse;

import com.example.greendao.dao.AnimalDao;
import com.example.greendao.dao.BodyDao;
import com.example.greendao.dao.HouseDao;
import com.example.greendao.dao.PersonDao;
import com.example.greendao.dao.PersonWithHouseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig animalDaoConfig;
    private final DaoConfig bodyDaoConfig;
    private final DaoConfig houseDaoConfig;
    private final DaoConfig personDaoConfig;
    private final DaoConfig personWithHouseDaoConfig;

    private final AnimalDao animalDao;
    private final BodyDao bodyDao;
    private final HouseDao houseDao;
    private final PersonDao personDao;
    private final PersonWithHouseDao personWithHouseDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        animalDaoConfig = daoConfigMap.get(AnimalDao.class).clone();
        animalDaoConfig.initIdentityScope(type);

        bodyDaoConfig = daoConfigMap.get(BodyDao.class).clone();
        bodyDaoConfig.initIdentityScope(type);

        houseDaoConfig = daoConfigMap.get(HouseDao.class).clone();
        houseDaoConfig.initIdentityScope(type);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        personWithHouseDaoConfig = daoConfigMap.get(PersonWithHouseDao.class).clone();
        personWithHouseDaoConfig.initIdentityScope(type);

        animalDao = new AnimalDao(animalDaoConfig, this);
        bodyDao = new BodyDao(bodyDaoConfig, this);
        houseDao = new HouseDao(houseDaoConfig, this);
        personDao = new PersonDao(personDaoConfig, this);
        personWithHouseDao = new PersonWithHouseDao(personWithHouseDaoConfig, this);

        registerDao(Animal.class, animalDao);
        registerDao(Body.class, bodyDao);
        registerDao(House.class, houseDao);
        registerDao(Person.class, personDao);
        registerDao(PersonWithHouse.class, personWithHouseDao);
    }
    
    public void clear() {
        animalDaoConfig.clearIdentityScope();
        bodyDaoConfig.clearIdentityScope();
        houseDaoConfig.clearIdentityScope();
        personDaoConfig.clearIdentityScope();
        personWithHouseDaoConfig.clearIdentityScope();
    }

    public AnimalDao getAnimalDao() {
        return animalDao;
    }

    public BodyDao getBodyDao() {
        return bodyDao;
    }

    public HouseDao getHouseDao() {
        return houseDao;
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

    public PersonWithHouseDao getPersonWithHouseDao() {
        return personWithHouseDao;
    }

}
